name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Archive iOS App
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Set Build Number
        id: set_build_number
        run: |
          buildNumber=${{ github.run_number }}
          echo "Setting build number to $buildNumber"
          echo "BUILD_NUMBER=$buildNumber" >> $GITHUB_ENV
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "RLLM/Info.plist"
          echo "Current Info.plist content:"
          /usr/libexec/PlistBuddy -c "Print" "RLLM/Info.plist"

      - name: Build Configuration
        run: |
          echo "📱 Building RLLM iOS app"
          echo "Build number: ${{ env.BUILD_NUMBER }}"
          echo "Xcode version:"
          xcodebuild -version
          echo "Swift version:"
          swift --version

      - name: Install Dependencies
        run: |
          if [ -f "Package.swift" ]; then
            swift package resolve
          fi

      - name: Create Export Options Plist
        run: |
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Build for Archive
        run: |
          xcodebuild clean build -scheme RLLM \
            -configuration Release \
            -sdk iphoneos \
            CURRENT_PROJECT_VERSION=${{ env.BUILD_NUMBER }} \
            MARKETING_VERSION=0.2.2 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO

      - name: Create Archive
        run: |
          xcodebuild archive \
            -scheme RLLM \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $RUNNER_TEMP/RLLM.xcarchive \
            CURRENT_PROJECT_VERSION=${{ env.BUILD_NUMBER }} \
            MARKETING_VERSION=0.2.2 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_BITCODE=NO \
            ONLY_ACTIVE_ARCH=NO

      - name: Create IPA
        run: |
          cd $RUNNER_TEMP/RLLM.xcarchive/Products/Applications
          mkdir Payload
          cp -r RLLM.app Payload/
          zip -r RLLM.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ${{ runner.temp }}/RLLM.xcarchive/Products/Applications/RLLM.ipa