name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Build Configuration
        run: |
          echo "📱 Building RLLM iOS app"
          echo "Xcode version:"
          xcodebuild -version
          echo "Swift version:"
          swift --version

      - name: Install Dependencies
        run: |
          if [ -f "Package.swift" ]; then
            swift package resolve
          fi

      - name: Build
        run: |
          xcodebuild clean build -scheme RLLM \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 