name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Archive iOS App
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Build Configuration
        run: |
          echo "📱 Building RLLM iOS app"
          echo "Xcode version:"
          xcodebuild -version
          echo "Swift version:"
          swift --version

      - name: Install Dependencies
        run: |
          if [ -f "Package.swift" ]; then
            swift package resolve
          fi

      - name: Create Export Options Plist
        run: |
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Build and Test
        run: |
          xcodebuild clean build -scheme RLLM \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=NO \
            -verbose | xcpretty && exit ${PIPESTATUS[0]}

      - name: Archive
        run: |
          xcodebuild archive \
            -scheme RLLM \
            -archivePath $RUNNER_TEMP/RLLM.xcarchive \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $RUNNER_TEMP/RLLM.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath $RUNNER_TEMP/build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ runner.temp }}/build/*.ipa