name: Build IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Install Dependencies
        run: |
          if [ -f "Package.swift" ]; then
            swift package resolve
          fi

      - name: Build IPA
        run: |
          xcodebuild clean archive \
            -scheme RLLM \
            -archivePath build/RLLM.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath build/RLLM.xcarchive \
            -exportPath build \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: RLLM
          path: build/RLLM.ipa